# Generated by Django 5.1.1 on 2024-11-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
